apiVersion: batch/v1
kind: Job
metadata:
  name: simulation-generator-agent
spec:
  completions: 1
  template:
    metadata:
      name: simulation-generator-agent-template
    spec:
      containers:
      - name: simulation-generator-agent-container
        image: mcanizo/cloudfmi-distributed-simulation-framework:simulation-generator-agent
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "python Simulation_Generator_Agent.py --url https://raw.githubusercontent.com/ikerlan2015/CloudFMI-Distributed-Simulation-Framework/master/Simulation_Generator_Agent/data/ --input_params input_params.json --anomalous_params anomalous_params.json --output_params output_params.json"]
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: POSTGRESQL_IP
          value: "<hostname or IP>"
        - name: POSTGRESQL_PORT
          value: "<db_port>"
        - name: POSTGRESQL_DB_NAME
          value: "<db_name>"
        - name: POSTGRESQL_DB_USER
          value: "<db_user>"
        - name: POSTGRESQL_DB_PASS
          value: "<db_password>"
      restartPolicy: OnFailure
